Repository SpecUp-2025/plun-2025, pull requests merged in 2025-10, with the labels that each got.

#67 파이썬 설정 및 sfu-server 도커파일 수정
  .gitignore
  docker-compose.yml
  frontend/nginx.conf
  python-backend/Dockerfile
  python-backend/app/config.py
  python-backend/app/services/db_service.py
  python-backend/app/services/recording_service.py
  sfu-server/. dockerignore
  sfu-server/Dockerfile
Labels: 설정

#70 채팅방 / 캘린더 일정 조회 시 입장 팀으로 조회
  backend/src/main/java/com/spec/plun/calendar/controller/CalendarController.java
  backend/src/main/java/com/spec/plun/calendar/dao/CalendarDAO.java
  backend/src/main/java/com/spec/plun/calendar/service/CalendarService.java
  backend/src/main/java/com/spec/plun/chat/controller/ChatController.java
  backend/src/main/java/com/spec/plun/chat/dao/ChatDAO.java
  backend/src/main/java/com/spec/plun/chat/entity/ChatRoom.java
  backend/src/main/java/com/spec/plun/chat/service/ChatService.java
  backend/src/main/resources/mappers/calendar/CalendarMapper.xml
  backend/src/main/resources/mappers/chat/ChatMapper.xml
  frontend/src/components/calendar/CalendarView.vue
  frontend/src/components/chat/ChatRoomList.vue
  frontend/src/components/meeting/MeetingNav.vue
  mariadb/sql/00_plun.sql
Labels: sql, 수정, 채팅, 캘린더

#72 알람 및 마이크 설정 변경
  backend/src/main/resources/mappers/alarm/alarmMapper.xml
  frontend/src/components/meeting/composables/useRecording.js
  python-backend/app/services/ai_service.py
Labels: 미팅, 알림
