Repository SpecUp-2025/plun-2025, pull requests merged in 2025-09, with the labels that each got.

#36 파이썬 설치 및 가상 환경 만들기
  backend-python/.env.example
  backend-python/.gitignore
  backend-python/app.py
  backend-python/requirements.txt
Labels: 파이썬

#40 검증없이 건너 띌 경로들을 함수에서 클래스로 수정
  backend/src/main/java/com/spec/plun/auth/config/PermitAllConfig.java
  backend/src/main/java/com/spec/plun/auth/config/SecurityConfig.java
  backend/src/main/java/com/spec/plun/auth/filter/JwtAuthenticationFilter.java
Labels: 설정, 수정, 인증

#42 음성 녹음, 파일 저장, 텍스트 변환 기능 추가
  backend-python/.env.example
  backend-python/.gitignore
  backend-python/app.py
  backend-python/requirements.txt
  python-backend/.env.example
  python-backend/.gitignore
  python-backend/README.md
  python-backend/app/config.py
  python-backend/app/main.py
  python-backend/app/routers/stt.py
  python-backend/app/services/audio_service.py
  python-backend/app/services/io_service.py
  python-backend/app/services/stt_service.py
  python-backend/requirements.txt
  python-backend/run.ps1
  python-backend/static/record_finalize.html
Labels: 설정, STT

#51 오류 이름 수정
  backend/src/main/java/com/spec/plun/auth/oauth2/social/NaverOauth.java
Labels: 소셜로그인

#52 캘린더 및 채팅 기능 추가
  backend/src/main/java/com/spec/plun/calendar/controller/CalendarWebSocketController.java
  backend/src/main/java/com/spec/plun/calendar/service/CalendarService.java
  backend/src/main/java/com/spec/plun/chat/controller/ChatController.java
  backend/src/main/java/com/spec/plun/chat/dto/ChatMessageRequestDTO.java
  backend/src/main/java/com/spec/plun/chat/dto/CreateChatRoomRequestDTO.java
  backend/src/main/java/com/spec/plun/chat/entity/ChatMessage.java
  backend/src/main/java/com/spec/plun/chat/service/ChatService.java
  backend/src/main/resources/mappers/alarm/alarmMapper.xml
  frontend/src/components/calendar/CalendarView.vue
  frontend/src/components/chat/ChatInput.vue
  frontend/src/components/chat/ChatMessage.vue
  frontend/src/components/chat/ChatRoom.vue
  frontend/src/components/chat/ChatRoomForm.vue
  frontend/src/components/chat/ChatRoomList.vue
  frontend/src/main/components/TeamMain.vue
  frontend/src/router/index.js
Labels: 수정, 채팅, 첨부파일, 알림, 캘린더

#53 로그인 css 추가 및 수정
  backend/src/main/java/com/spec/plun/email/service/EmailSendInviteService.java
  backend/src/main/java/com/spec/plun/email/service/EmailService.java
  backend/src/main/java/com/spec/plun/team/controller/TeamController.java
  backend/src/main/java/com/spec/plun/team/dao/TeamDAO.java
  backend/src/main/java/com/spec/plun/team/dto/TeamDTO.java
  backend/src/main/java/com/spec/plun/team/dto/TeamsInvitationDTO.java
  backend/src/main/java/com/spec/plun/team/service/TeamService.java
  backend/src/main/resources/mappers/team/Team.xml
  frontend/src/assets/css/auth.css
  frontend/src/assets/css/code.css
  frontend/src/assets/css/home.css
  frontend/src/assets/icons/PLUN.png
  frontend/src/auth/components/LoginForm.vue
  frontend/src/main/HomeFooter.vue
  frontend/src/main/HomeHeader.vue
  frontend/src/member/components/FindPassword.vue
  frontend/src/member/components/Logo.vue
  frontend/src/member/components/MemberDetail.vue
  frontend/src/member/components/Register.vue
  frontend/src/member/components/TeamCreate.vue
  frontend/src/member/components/TeamList.vue
  frontend/src/member/components/TeamSetting.vue
  frontend/src/member/components/TeamsInvitation.vue
  frontend/src/router/index.js
Labels: 설정, sql, 수정, 로그인, 팀, 알림, 비밀번호, 목록, 수락, 초대, 소셜로그인, css

#56 회의방 로직 완성
  frontend/README.md
  frontend/src/components/meeting/LocalMedia.vue
  frontend/src/components/meeting/MeetingPrejoinModal.vue
  frontend/src/components/meeting/MeetingRoom.vue
  frontend/src/components/meeting/MeetingRoomInfoModal.css
  frontend/src/components/meeting/RemoteMedia.vue
  frontend/src/components/meeting/components/ControlsBar.vue
  frontend/src/components/meeting/components/RecordingControls.vue
  frontend/src/components/meeting/components/VideoGrid.vue
  frontend/src/components/meeting/composables/useMediaControls.js
  frontend/src/components/meeting/composables/useRecording.js
  frontend/src/components/meeting/composables/useSfu.js
  frontend/src/styles/components/modal.css
  frontend/src/util/sfuClient.js
  frontend/vite.config.js
  python-backend/.env.example
  python-backend/.gitignore
  python-backend/app/config.py
  python-backend/app/main.py
  python-backend/app/routers/__init__.py
  python-backend/app/routers/recording.py
  python-backend/app/routers/stt.py
  python-backend/app/routers/summary.py
  python-backend/app/routers/transcript.py
  python-backend/app/services/ai_service.py
  python-backend/app/services/audio_service.py
  python-backend/app/services/db_service.py
  python-backend/app/services/io_service.py
  python-backend/app/services/recording_service.py
  python-backend/app/services/stt_service.py
  python-backend/app/services/summary_llm.py
  python-backend/app/services/summary_parse.py
  python-backend/main.py
  python-backend/requirements.txt
  python-backend/run.ps1
  python-backend/static/record_finalize.html
  sfu-server/src/server.js
  sql/plun.sql
Labels: 설정, sql, 수정, 미팅, 캘린더, AI요약

#57 채팅 / 캘린더 / 알림 / 첨부파일 / css 전체 수정
  backend/src/main/java/com/spec/plun/alarm/service/AlarmService.java
  backend/src/main/java/com/spec/plun/calendar/controller/CalendarWebSocketController.java
  backend/src/main/java/com/spec/plun/calendar/service/CalendarService.java
  backend/src/main/java/com/spec/plun/chat/controller/ChatController.java
  backend/src/main/java/com/spec/plun/chat/dao/ChatDAO.java
  backend/src/main/java/com/spec/plun/chat/service/ChatService.java
  backend/src/main/resources/mappers/calendar/CalendarMapper.xml
  backend/src/main/resources/mappers/chat/ChatMapper.xml
  frontend/src/components/alarm/AlarmDropdown.vue
  frontend/src/components/calendar/CalendarRegModal.vue
  frontend/src/components/calendar/CalendarView.vue
  frontend/src/components/chat/ChatInput.vue
  frontend/src/components/chat/ChatMain.vue
  frontend/src/components/chat/ChatMessage.vue
  frontend/src/components/chat/ChatNav.vue
  frontend/src/components/chat/ChatRoom.vue
  frontend/src/components/chat/ChatRoomForm.vue
  frontend/src/components/chat/ChatRoomList.vue
  frontend/src/components/layout/HeaderBar.vue
  frontend/src/components/layout/SideNav.vue
  frontend/src/components/meeting/MeetingNav.vue
  frontend/src/main/components/TeamMain.vue
  frontend/src/store/useAlarmStore.js
Labels: 수정, 채팅, 첨부파일, 알림, 캘린더

#60 사이드 바 / 초대보관함 / 팀리스트 수정
  backend/src/main/java/com/spec/plun/team/service/TeamService.java
  frontend/src/components/alarm/AlarmDropdown.vue
  frontend/src/components/calendar/CalendarView.vue
  frontend/src/components/chat/ChatNav.vue
  frontend/src/components/chat/ChatRoom.vue
  frontend/src/components/chat/ChatRoomList.vue
  frontend/src/components/layout/HeaderBar.vue
  frontend/src/components/layout/SideNav.vue
  frontend/src/components/meeting/MeetingNav.vue
  frontend/src/main/components/TeamMain.vue
  frontend/src/member/components/TeamList.vue
  frontend/src/member/components/TeamsInvitation.vue
  sql/plun.sql
Labels: sql, 수정, 채팅, 알림, 목록

#64 refresh 토큰 탈취 및 만료시 로그인
  frontend/src/util/interceptors.js
  mariadb/sql/00_plun.sql
  mariadb/sql/01_insert.sql
Labels: 토큰

#66 09.30 회의 기능 수정 및 알람 추가
  backend/src/main/java/com/spec/plun/alarm/controller/AlarmController.java
  backend/src/main/java/com/spec/plun/alarm/service/AlarmService.java
  backend/src/main/java/com/spec/plun/auth/config/PermitAllConfig.java
  backend/src/main/java/com/spec/plun/meeting/room/MeetingRoomController.java
  backend/src/main/java/com/spec/plun/meeting/room/MeetingRoomService.java
  frontend/src/components/alarm/AlarmDropdown.vue
  frontend/src/components/calendar/CalendarView.vue
  frontend/src/components/meeting/MeetingRoom.vue
  frontend/src/components/meeting/composables/useRecording.js
  frontend/src/main/components/TeamMain.vue
  frontend/src/store/useAlarmStore.js
  python-backend/app/config.py
  python-backend/app/routers/recording.py
  python-backend/app/services/ai_service.py
  python-backend/app/services/recording_service.py
Labels: 인증, 알림, AI요약
