Repository SpecUp-2025/plun-2025, pull requests merged in 2025-08, with the labels that each got.

#2 sql문 생성
  sql/plun.sql
Labels: sql

#4 vue 버전 수정
  frontend/package-lock.json
Labels: 수정

#5 수정
  frontend/src/router/index.js
Labels: 수정

#6 회의 관련 테이블 초안 작성 및 역할 코드 샘플 데이터 변경
  sql/plun.sql
Labels: sql

#9 실시간 채팅 구현 ( 로그인 기능 X / 첨부파일 기능 X / 추가 수정 예정)
  backend/src/main/java/com/spec/plun/BackendApplication.java
  backend/src/main/java/com/spec/plun/chat/controller/ChatController.java
  backend/src/main/java/com/spec/plun/chat/dao/ChatDAO.java
  backend/src/main/java/com/spec/plun/chat/entity/ChatMember.java
  backend/src/main/java/com/spec/plun/chat/entity/ChatMessage.java
  backend/src/main/java/com/spec/plun/chat/entity/ChatRoom.java
  backend/src/main/java/com/spec/plun/chat/entity/MessageType.java
  backend/src/main/java/com/spec/plun/chat/service/ChatService.java
  backend/src/main/resources/mappers/chat/ChatMapper.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/chat/ChatInput.vue
  frontend/src/components/chat/ChatMessage.vue
  frontend/src/components/chat/ChatRoom.vue
  frontend/src/components/chat/ChatRoomForm.vue
  frontend/src/components/chat/ChatRoomList.vue
  frontend/src/router/index.js
  frontend/vite.config.js
Labels: chat

#10 WebSocketConfig / SecurityConfig 추가 및 수정
  backend/src/main/java/com/spec/plun/auth/config/SecurityConfig.java
  backend/src/main/java/com/spec/plun/chat/config/WebSocketConfig.java
Labels: 채팅

#12 metadata추가
  .gitignore
Labels: 설정

#15 axios 헤더 토큰 자동 장착
  backend/src/main/java/com/spec/plun/auth/controller/PingController.java
  backend/src/main/java/com/spec/plun/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/spec/plun/auth/service/AccessTokenService.java
  backend/src/main/java/com/spec/plun/auth/service/RefreshTokenService.java
  frontend/src/components/LoginForm.vue
  frontend/src/components/Success.vue
  frontend/src/store/userStore.js
  frontend/src/util/interceptors.js
Labels: 설정, 토큰, 로그인, 인증

#16 토큰 시간 변경
  backend/src/main/java/com/spec/plun/auth/service/AccessTokenService.java
Labels: 토큰

#18 Meeting
  backend/src/main/java/com/spec/plun/meeting/dto/MeetingCreateRequest.java
  backend/src/main/java/com/spec/plun/meeting/dto/MemberDTO.java
  backend/src/main/java/com/spec/plun/meeting/room/MeetingRoomController.java
  backend/src/main/java/com/spec/plun/meeting/room/MeetingRoomDAO.java
  backend/src/main/java/com/spec/plun/meeting/room/MeetingRoomMapper.java
  backend/src/main/java/com/spec/plun/meeting/room/MeetingRoomService.java
  backend/src/main/java/com/spec/plun/meeting/webrtc/SignalController.java
  backend/src/main/java/com/spec/plun/team/controller/TeamController.java
  backend/src/main/java/com/spec/plun/team/dao/TeamDAO.java
  backend/src/main/java/com/spec/plun/team/dto/TeamMemberDTO.java
  backend/src/main/java/com/spec/plun/team/service/TeamService.java
  backend/src/main/resources/mappers/MeetingRoomMapper.xml
  backend/src/main/resources/mappers/meeting/MeetingRoomMapper.xml
  backend/src/main/resources/mappers/team/TeamMapper.xml
  backend/src/test/java/com/spec/plun/meeting/room/MeetingRoomServiceTest.java
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/meeting/Meeting.vue
  frontend/src/components/meeting/MeetingCreateModal.vue
  frontend/src/components/meeting/MeetingTest.vue
  frontend/src/components/meeting/SignalTest.vue
  frontend/src/router/index.js
  frontend/vite.config.js
Labels: 설정, 미팅, 팀

#20 AccessToken 만료시 RefreshToken 이용해서 발급
  backend/build.gradle
  backend/src/main/java/com/spec/plun/auth/DTO/RefreshTokenRequest.java
  backend/src/main/java/com/spec/plun/auth/controller/AuthController.java
  backend/src/main/java/com/spec/plun/auth/service/AccessTokenService.java
  backend/src/main/java/com/spec/plun/auth/service/AuthService.java
  backend/src/main/java/com/spec/plun/auth/service/RefreshTokenService.java
  frontend/src/auth/components/Success.vue
  frontend/src/store/userStore.js
  frontend/src/util/interceptors.js
Labels: 설정, 수정, 토큰, 로그인

#21 라우터 폴더 정리
  frontend/src/router/index.js
Labels: 설정, 수정

#23 채팅 / 첨부파일 기능 구현
  backend/src/main/java/com/spec/plun/attachment/controller/AttachmentController.java
  backend/src/main/java/com/spec/plun/attachment/dao/AttachmentDAO.java
  backend/src/main/java/com/spec/plun/attachment/entity/Attachment.java
  backend/src/main/java/com/spec/plun/attachment/service/AttachmentService.java
  backend/src/main/java/com/spec/plun/chat/controller/ChatController.java
  backend/src/main/java/com/spec/plun/chat/dto/ChatMessageRequestDTO.java
  backend/src/main/java/com/spec/plun/chat/entity/ChatMessage.java
  backend/src/main/java/com/spec/plun/chat/service/ChatService.java
  backend/src/main/resources/mappers/attachment/AttachmentMapper.xml
  backend/src/main/resources/mappers/chat/ChatMapper.xml
  frontend/src/components/chat/ChatInput.vue
  frontend/src/components/chat/ChatMessage.vue
  frontend/src/components/chat/ChatRoom.vue
Labels: 채팅, 첨부파일

#26 채팅 및 첨부파일 기능 추가
  backend/src/main/java/com/spec/plun/auth/config/SecurityConfig.java
  backend/src/main/java/com/spec/plun/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/spec/plun/chat/controller/ChatController.java
  backend/src/main/java/com/spec/plun/chat/dao/ChatDAO.java
  backend/src/main/java/com/spec/plun/chat/service/ChatService.java
  backend/src/main/resources/mappers/chat/ChatMapper.xml
  frontend/src/components/chat/ChatInput.vue
  frontend/src/components/chat/ChatMessage.vue
  frontend/src/components/chat/ChatRoom.vue
  frontend/src/components/chat/ChatRoomForm.vue
  frontend/src/components/chat/ChatRoomList.vue
Labels: 수정, 토큰, 채팅, 첨부파일

#29 Meeting
  backend/src/main/java/com/spec/plun/meeting/DbHealthMapper.java
  backend/src/main/java/com/spec/plun/meeting/HealthController.java
  backend/src/main/java/com/spec/plun/meeting/dto/MeetingCreateRequest.java
  backend/src/main/java/com/spec/plun/meeting/dto/MeetingRoomListDto.java
  backend/src/main/java/com/spec/plun/meeting/dto/MemberDTO.java
  backend/src/main/java/com/spec/plun/meeting/room/MeetingRoomController.java
  backend/src/main/java/com/spec/plun/meeting/room/MeetingRoomDAO.java
  backend/src/main/java/com/spec/plun/meeting/room/MeetingRoomService.java
  backend/src/main/java/com/spec/plun/meeting/webrtc/SignalController.java
  backend/src/main/resources/mappers/meeting/MeetingRoomMapper.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/meeting/Meeting.vue
  frontend/src/components/meeting/MeetingCreateModal.vue
  frontend/src/components/meeting/MeetingMain.vue
  frontend/src/components/meeting/MeetingPrejoinModal.vue
  frontend/src/components/meeting/MeetingRoom.vue
  frontend/src/components/meeting/MeetingTest.vue
  frontend/src/components/meeting/SignalTest.vue
  frontend/src/router/index.js
  frontend/src/util/sfuClient.js
  frontend/vite.config.js
  sfu-server/.gitignore
  sfu-server/package-lock.json
  sfu-server/package.json
  sfu-server/src/server.js
Labels: 수정, 미팅

#30 팀 생성 및 초대 메일 발송
  backend/src/main/java/com/spec/plun/auth/controller/AuthController.java
  backend/src/main/java/com/spec/plun/email/service/EmailSendInviteService.java
  backend/src/main/java/com/spec/plun/team/controller/TeamController.java
  backend/src/main/java/com/spec/plun/team/dao/TeamDAO.java
  backend/src/main/java/com/spec/plun/team/dto/TeamCreateRequest.java
  backend/src/main/java/com/spec/plun/team/dto/TeamCreateResponse.java
  backend/src/main/java/com/spec/plun/team/service/TeamService.java
  backend/src/main/resources/mappers/team/TeamMapper.xml
  frontend/src/auth/components/LoginForm.vue
  frontend/src/member/components/TeamCreate.vue
  frontend/src/member/components/TeamList.vue
  frontend/src/router/index.js
Labels: 팀, 이메일

#32 알림 패키지 추가 및 기능 구현 / 채팅 + 알림기능 추가
  backend/src/main/java/com/spec/plun/alarm/controller/AlarmController.java
  backend/src/main/java/com/spec/plun/alarm/dao/AlarmDAO.java
  backend/src/main/java/com/spec/plun/alarm/entity/Alarm.java
  backend/src/main/java/com/spec/plun/alarm/service/AlarmService.java
  backend/src/main/java/com/spec/plun/attachment/service/AttachmentService.java
  backend/src/main/java/com/spec/plun/chat/controller/ChatController.java
  backend/src/main/java/com/spec/plun/chat/dao/ChatDAO.java
  backend/src/main/java/com/spec/plun/chat/entity/ChatMember.java
  backend/src/main/java/com/spec/plun/chat/entity/ChatMessage.java
  backend/src/main/java/com/spec/plun/chat/service/ChatService.java
  backend/src/main/resources/mappers/alarm/alarmMapper.xml
  backend/src/main/resources/mappers/chat/ChatMapper.xml
  frontend/src/components/alarm/AlarmDropdown.vue
  frontend/src/components/chat/ChatInput.vue
  frontend/src/components/chat/ChatMessage.vue
  frontend/src/components/chat/ChatRoom.vue
  frontend/src/components/chat/ChatRoomList.vue
  frontend/src/router/index.js
Labels: 수정, 채팅, 첨부파일, 알림

#33 회의 에러 코드 수정
  frontend/src/components/meeting/MeetingNav.vue
  frontend/src/components/meeting/MeetingPrejoinModal.vue
  frontend/src/main/components/TeamMain.vue
  frontend/src/router/index.js
Labels: 수정, 미팅

#34 캘린더 패키지 생성 및 기능 구현중
  backend/src/main/java/com/spec/plun/calendar/controller/CalendarController.java
  backend/src/main/java/com/spec/plun/calendar/dao/CalendarDAO.java
  backend/src/main/java/com/spec/plun/calendar/entity/Calendar.java
  backend/src/main/java/com/spec/plun/calendar/entity/CalendarDetail.java
  backend/src/main/java/com/spec/plun/calendar/service/CalendarService.java
  backend/src/main/resources/mappers/calendar/CalendarMapper.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/calendar/CalendarModal.vue
  frontend/src/components/calendar/CalendarView.vue
  frontend/src/components/chat/ChatRoomList.vue
  frontend/src/main.js
  frontend/src/router/index.js
Labels: 수정, 캘린더
